version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_performance
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: performance
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
